#//-----------------------------------------------------------------------------
#//	SERVER_CSTRIKE15.VPC
#//
#//	Project Script
#//-----------------------------------------------------------------------------

#There are other projects in this folder, but this cmake is focused towards csgo a.k.a. cstrike15

cmake_minimum_required(VERSION 3.16)
set(GAMENAME "tf")
set(NOSTINKYLINKIES "1")
set(GENERATED_PROTO_DIR "${SRCDIR}/game/client/generated_proto")
include(${CMAKE_MODULE_PATH}/protobuf_builder.cmake)
add_definitions(-DTF_CLIENT_DLL -DUSES_ECON_ITEMS -DENABLE_GC_MATCHMAKING -DGLOWS_ENABLE -DUSE_DYNAMIC_ASSET_LOADING -DVOTING_ENABLED -DNEXT_BOT ) #-DSIXENSE


include( ./client_base.cmake )
include( ./client_econ_base.cmake )

if( LINUXALL )
    target_compile_options(${OUTBINNAME} PRIVATE "-Wno-narrowing")
endif()
include_directories(${SRCDIR}/game/shared/tf)
include_directories(${SRCDIR}/game/client/tf)
include_directories(${SRCDIR}/game/client/tf/vgui)
include_directories(${SRCDIR}/game/client/econ)
include_directories(${SRCDIR}/game/shared/econ)
include_directories(${SRCDIR}/gcsdk/steamextra)
include_directories(${GENERATED_PROTO_DIR}/econ)
#tf_gcmessages_include
TargetBuildAndAddProto( ${OUTBINNAME} ${SRCDIR}/game/shared/tf/tf_gcmessages.proto "${GENERATED_PROTO_DIR}")
TargetBuildAndAddProto( ${OUTBINNAME} ${SRCDIR}/gcsdk/gcsystemmsgs.proto ${GENERATED_PROTO_DIR} )
TargetBuildAndAddProto( ${OUTBINNAME} ${SRCDIR}/gcsdk/steammessages.proto ${GENERATED_PROTO_DIR} )
TargetBuildAndAddProto( ${OUTBINNAME} ${SRCDIR}/game/shared/base_gcmessages.proto ${GENERATED_PROTO_DIR} )
#TargetBuildAndAddProto( ${OUTBINNAME} ${SRCDIR}/game/shared/econ/econ_gcmessages.proto "${GENERATED_PROTO_DIR}") //temp
#TargetBuildAndAddProto( ${OUTBINNAME} ${SRCDIR}/game/shared/cstrike15/cstrike15_gcmessages.proto "${GENERATED_PROTO_DIR}")
target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_gcmessages.cpp")

#$Project "Client (TF)"

		#-$File	"${SRCDIR}/game/shared/weapon_parse_default.cpp")

	#$Folder	"Source Files"
target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/client/abuse_report.cpp")
target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/client/abuse_report_ui.cpp")
target_sources(${OUTBINNAME} PRIVATE "tf/tf_abuse_report.cpp")
target_sources(${OUTBINNAME} PRIVATE "c_team_objectiveresource.cpp")
target_sources(${OUTBINNAME} PRIVATE "c_team_train_watcher.cpp")
target_sources(${OUTBINNAME} PRIVATE "hud_base_account.cpp")
target_sources(${OUTBINNAME} PRIVATE "tf/hud_basedeathnotice.cpp")
target_sources(${OUTBINNAME} PRIVATE "hud_controlpointicons.cpp")
target_sources(${OUTBINNAME} PRIVATE "hud_voicestatus.cpp")
target_sources(${OUTBINNAME} PRIVATE "hud_vguiscreencursor.cpp")
target_sources(${OUTBINNAME} PRIVATE "hud_baseachievement_tracker.cpp")
target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/client/hud_vote.cpp")
target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/motd.cpp")
target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/playerclass_info_parse.cpp")
target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/teamplay_round_timer.cpp")
target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/common/ServerBrowser/blacklisted_server_manager.cpp")
target_sources(${OUTBINNAME} PRIVATE "TeamBitmapImage.cpp")
target_sources(${OUTBINNAME} PRIVATE "voice_menu.cpp")
target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/common/GameUI/scriptobject.cpp")
target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/common/GameUI/cvarslider.cpp")
		#$Folder	"Economy"
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_item_inventory.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_item_wearable.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_item_system.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_item_schema.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_quest_editor_panel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_quest_restriction.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_wardata.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_rating_data.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_ladder_data.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_survey_questions.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_xp_source.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_notification.cpp")

		#$Folder "Economy Client"
	target_sources(${OUTBINNAME} PRIVATE "econ/item_selection_panel.cpp")
		#$Folder	"Store"
	target_sources(${OUTBINNAME} PRIVATE "econ/store/store_page_halloween.cpp")

		#$Folder "TF Economy Client Overrides"
	target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_item_pickup_panel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/vgui/store/tf_store.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/vgui/store/tf_store_panel_base.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/vgui/store/tf_store_page_base.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/vgui/store/tf_store_preview_item_base.cpp")


			#$Folder "v1"
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/store/v1/tf_store_page.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/store/v1/tf_store_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/store/v1/tf_store_preview_item.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/store/v1/tf_store_page_maps.cpp")

			#$Folder "v2"
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/store/v2/tf_store_page2.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/store/v2/tf_store_panel2.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/store/v2/tf_store_preview_item2.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/store/v2/tf_store_page_maps2.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/store/v2/tf_store_mapstamps_info_dialog.cpp")

		#$Folder	"TF"
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_passtime_gun.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/passtime_game_events.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/passtime_convars.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_func_passtime_goal.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_passtime_ball.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_passtime_logic.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_passtime.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_passtime_ball_offscreen_arrow.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_passtime_reticle.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_glow.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/achievements_tf.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/achievements_tf_demoman.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/achievements_tf_engineer.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/achievements_tf_heavy.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/achievements_tf_medic.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/achievements_tf_pyro.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/achievements_tf_scout.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/achievements_tf_sniper.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/achievements_tf_soldier.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/achievements_tf_spy.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/achievements_tf_replay.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/achievements_tf_maps.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/achievements_tf_mvm.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/achievements_tf_halloween.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/baseobject_shared.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_autorp.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_baseobject.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_entity_bird.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_entity_currencypack.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_func_forcefield.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_func_respawnroom.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_func_capture_zone.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_obj_dispenser.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_obj_sapper.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_obj_sentrygun.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_obj_teleporter.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_stickybolt.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_death_callingcard.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_playerattachedmodel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_playerrelativemodel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_ammo_pack.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_buff_banner.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_fx.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_haptics.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_objective_resource.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_player.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_playerresource.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_team.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/clientmode_tf.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/entity_capture_flag.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/Multiplayer/multiplayer_animstate.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/teammaterialproxy.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_demo_support.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_fx_blood.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_fx_christmaslights.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_fx_ejectbrass.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_fx_impacts.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_fx_explosions.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_fx_muzzleflash.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_fx_particleeffect.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_fx_taunteffects.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_fx_shared.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_fx_tracers.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_gamemovement.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_gamerules.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_classdata.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_account.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_achievement_tracker.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_alert.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_ammostatus.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_annotationspanel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_arena_capturepoint.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_arena_class_layout.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_item_progress_tracker.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_arena_notification.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_arena_player_count.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_arena_vs_panel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_arena_winpanel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_bowcharge.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/entity_bonuspack.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/entity_halloween_pickup.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_boss_health.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_building_status.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_chat.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_match_status.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_crosshair.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_damageindicator.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_demomancharge.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_demomanpipes.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_deathnotice.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_disguise_status.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_escort.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_flagstatus.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_robot_destruction_status.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_freezepanel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_inspectpanel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_itemeffectmeter.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_mediccallers.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_mediccharge.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_menu_engy_build.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_menu_eureka_teleport.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_menu_engy_destroy.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_menu_spy_build.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_menu_spy_disguise.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_menu_taunt_selection.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_notification_panel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_objectivestatus.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_playerstatus.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_pve_winpanel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_sapper_charge.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_scope.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_stalemate.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_tournament.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_statpanel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_mann_vs_machine_loss.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_mann_vs_machine_stats.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_mann_vs_machine_status.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_mann_vs_machine_scoreboard.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_mann_vs_machine_victory.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_disconnect_prompt.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_training.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_gamestats.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_mainmenuoverride.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_minigame.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_saxxycontest.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_spectator_extras.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_target_id.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_teamgoal.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_teamgoal_tournament.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_teamswitch.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_trainingmessage.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_training_complete.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_waitingforplayers_panel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_weaponselection.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_hud_winpanel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_imagepanel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_item_card_panel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_item_inspection_panel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_particlepanel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_ping_panel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_input_main.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_presence.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_proxyentity.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_proxyplayer.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_rendertargets.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_revive.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_shared_content_manager.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_steamstats.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_teamstatus.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_time_panel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_tips.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_viewrender.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_coaching.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_gameserver_management.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_consumables.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_mapinfo.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_halloween.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_monster_resource.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_freeaccount.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_mvm_boss_progress_user.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_notification.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_taunt_prop.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/quest_objective_trackers.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/quest_objective_manager.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/shared_object_tracker.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_halloween_souls_pickup.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_item.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_obj_baseupgrade_shared.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_item_powerup_bottle.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_condition.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_player_shared.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_playeranimstate.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_playerclass_info_parse.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_playerclass_shared.cpp")
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_prediction.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_projectile_base.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_projectile_nail.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_shareddefs.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_duckleaderboard.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_usermessages.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_viewmodel.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_generic_bomb.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_pumpkin_bomb.cpp")
			#//$File	"${SRCDIR}/game/shared/tf/tf_target_dummy.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/steamworks_gamestats.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_logic_halloween_2014.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_logic_robot_destruction.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_robot_destruction_robot.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_logic_player_destruction.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_gamestats_shared.cpp")


			#$Folder	"Weapon"
		target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_projectile_arrow.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_projectile_energy_ball.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_projectile_energy_ring.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_projectile_flare.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_projectile_rocket.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/c_tf_weapon_builder.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_dropped_weapon.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_bat.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_bonesaw.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_bottle.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_buff_item.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_club.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_compound_bow.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_fireaxe.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_fists.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_flamethrower.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_grapplinghook.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_grenade_pipebomb.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_grenadelauncher.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_invis.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_jar.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_knife.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_laser_pointer.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_lunchbox.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_medigun.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_minigun.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_parse.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_parachute.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_particle_cannon.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_pda.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_pipebomblauncher.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_pistol.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_raygun.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_revolver.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_rocketlauncher.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_shotgun.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_shovel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_smg.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_sniperrifle.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_sword.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_syringegun.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_throwable.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_wrench.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weaponbase.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weaponbase_grenadeproj.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weaponbase_merasmus_grenade.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weaponbase_gun.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weaponbase_melee.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weaponbase_rocket.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_flaregun.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_wearable_item_demoshield.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_wearable_levelable_item.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_weapon_mechanical_arm.cpp")

			#$Folder	"Economy"
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/econ/econ_claimcode.cpp")

			#$Folder "Steam Workshop"
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/workshop/ugc_utils.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/client/steampublishedfiles/publish_file_dialog.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/client/tf/workshop/published_files.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/client/tf/workshop/item_import.cpp")         #[$WORKSHOP_IMPORT_ENABLE]
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/client/bsp_utils.cpp")

			#$Folder	"vgui"
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/backgroundpanel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/blueprint_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/crafting_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/character_info_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/charinfo_armory_subpanel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/charinfo_loadout_subpanel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/class_loadout_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/dynamic_recipe_subpanel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/drawing_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/crate_detail_panels.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/quest_log_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/quest_item_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/quest_notification_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/item_ad_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/item_quickswitch.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/item_slot_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/loadout_preset_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_match_join_handlers.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_matchmaking_dashboard_new_match_found.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_matchmaking_dashboard_next_map_voting.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_matchmaking_dashboard_next_map_winner.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_matchmaking_dashboard.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/modelimagepanel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/ObjectControlPanel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/softline.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/testitem_root.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/testitem_dialog.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_badge_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_classmenu.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_clientscoreboard.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_controls.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_giveawayitempanel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_mapinfomenu.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_playermodelpanel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_intromenu.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_match_summary.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_roundinfo.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_spectatorgui.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_playerpanel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_teammenu.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_arenateammenu.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_statsummary.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_textwindow.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_viewport.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_vgui_video.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/select_player_dialog.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/vgui_critpanel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/vgui_pda_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/vgui_rootpanel_tf.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/vgui_rotation_slider.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_training_ui.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_mouseforwardingpanel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_lobbypanel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_lobbypanel_mvm.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_lobbypanel_comp.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_lobbypanel_casual.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_lobby_container_frame.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_lobby_container_frame_comp.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_lobby_container_frame_casual.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_lobby_container_frame_mvm.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_layeredmappanel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_pvp_rank_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_warinfopanel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_asyncpanel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/tf_leaderboardpanel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/strange_count_transfer_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/collection_crafting_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/halloween_offering_panel.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/sc_hinticon.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/vgui/report_player_dialog.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/tf_streams.cpp")

			#$Folder	"halloween"
		target_sources(${OUTBINNAME} PRIVATE "tf/halloween/c_headless_hatman.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/halloween/c_eyeball_boss.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/halloween/c_merasmus.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/halloween/c_merasmus_dancer.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/halloween/c_zombie.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/halloween/eyeball_boss/teleport_vortex.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/halloween/tf_weapon_spellbook.cpp")

			#$Folder	"Bot NPC"
		target_sources(${OUTBINNAME} PRIVATE "tf/bot_npc/c_bot_npc.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/bot_npc/c_bot_npc_minion.cpp")
			#$Folder "MapEntities"
		target_sources(${OUTBINNAME} PRIVATE "tf/bot_npc/map_entities/c_tf_bot_hint_engineer_nest.cpp")
			#$Folder	"NextBot"
		target_sources(${OUTBINNAME} PRIVATE "NextBot/C_NextBot.cpp")
			#$Folder	"PvE"
		target_sources(${OUTBINNAME} PRIVATE "tf/player_vs_environment/c_boss_alpha.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/player_vs_environment/c_tf_base_boss.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/player_vs_environment/c_tf_tank_boss.cpp")
		target_sources(${OUTBINNAME} PRIVATE "tf/player_vs_environment/c_tf_upgrades.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_mann_vs_machine_stats.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_upgrades_shared.cpp")


			#$Folder	"Matchmaking"
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/client/tf/tf_gc_client.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/party.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/playergroup.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/lobby.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_party.cpp")

				#// For now, clients are subscribed to the server lobby object. In the future we want to give clients a
				#// smaller subset, at which point we don't need this file (and the file should be moved shared->server)
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_lobby_server.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_matchmaking_shared.cpp")
		target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/tf/tf_match_description.cpp")


		#$Folder	"game_controls"
	target_sources(${OUTBINNAME} PRIVATE "game_controls/buymenu.cpp")
	target_sources(${OUTBINNAME} PRIVATE "game_controls/buysubmenu.cpp")
	target_sources(${OUTBINNAME} PRIVATE "game_controls/classmenu.cpp")

		#$Folder	"IFM"
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/weapon_ifmbase.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/weapon_ifmbasecamera.cpp")
	target_sources(${OUTBINNAME} PRIVATE "${SRCDIR}/game/shared/weapon_ifmsteadycam.cpp")

		#$Folder "Replay"
	target_sources(${OUTBINNAME} PRIVATE "tf/tf_replay.cpp")

	#$Folder	"Link libraries"
		#$ImplibExternal	"steamnetworkingsockets"
